### ISSUE TITLE
Support GitHub Actions

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/polyglot-release#24]
### 🤔 What's the problem you're trying to solve?

Releasing GitHub Actions is just as error prone as the others.

### ✨ What's your proposed solution?

`polyglot-release ....something....` because github actions are monoglot (#19)

### ⛏ Have you considered any alternatives or workarounds?

Alcohol comes to mind.

**Comment by mattwynne** [comment]
Right on. These are nice and simple because we can just push to the release branch and (assuming the project's release config is set up correctly) the [github-release](https://github.com/cucumber/action-create-github-release) action will create a tag which is all that's needed to release an action.

e.g. https://github.com/cucumber/action-publish-mvn/blob/main/.github/workflows/release.yaml#L15
